#!/usr/bin/env bash

##
# inside_container function (b7486571adb3beb7255acc0fbeea60703e0054f40a074e194119407e75eb633b)
# @version (2025-04-08)
##
declare -F inside_container &>/dev/null || {
    inside_container(){
        grep -qE '/docker/|/lxc/' /proc/1/cgroup 2>/dev/null || [ -f /.dockerenv ]
    }}

[ "${BASH_SOURCE[0]}" = "$0" ] && inside_container "$@"
