#!/usr/bin/env bash

##
# inside_container function (8b99f0cad4732d47246098b67df3e9a10945e844c2e909e07fb2036270416cfd)
# @version (2025-04-08)
##
declare -F inside_container &>/dev/null || {
  inside_container(){
    grep -qE '/docker/|/lxc/' /proc/1/cgroup 2>/dev/null || [ -f /.dockerenv ]
  }
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && inside_container "$@"
