#!/usr/bin/env bash

##
# is_available function
# @version (2025-04-10)
# @checksum 5bc075155dd402bb3a7e685ca38899a3e9dc03bd4430f159a9c95f9646bb2b23
# @alias sys_command, is_installed
##
declare -F is_available &>/dev/null || {
    is_available() {
        declare ref; if [[ "$1" == --var=* ]]; then ref="${1#*=}"; declare -n val="$ref"; shift; else local val; fi;
        [ "${is_available__cache["$1"]}" == "" ] && is_available__cache["$1"]=$( type -t -- "$1" 2>/dev/null )
        val="${is_available__cache["$1"]}"
        [ "$ref" ] || { [ "$val" ] && echo "$val"; }
        [ "$val" != "" ]
    }
    
    declare -A is_available__cache=()
}

[ "${BASH_SOURCE[0]}" = "$0" ] && is_available "$@"
