#!/usr/bin/env bash

##
# is_running function
# @version (2025-04-13)
# @checksum ae92f349d9ab059b84f919a048e35e0b15b0eecb8d61c33c94e876c687b16fe2
##
declare -F is_running &>/dev/null || {
    is_running() {
        [ $# -eq 0 ] && { echo "Usage: is_running <process_name> [more...]"; return 1; }
        for proc in "$@"; do pgrep -x "$proc" >/dev/null 2>&1 || return 2; done
    }
}

[ "${BASH_SOURCE[0]}" = "$0" ] && is_running "$@"
