#!/usr/bin/env bash

##
# ls function (edc4680eb6bc8e7ed8f7057ef7cb96c0059b407ba2b665345f82234be70cbc3a)
# @version (2025-04-08)
##
declare -F ls &>/dev/null || {
    # ls() - Enhanced ls for Git Bash (or Linux)
    # Also lists mounted drives (e.g. /c, /d) or remote NFS mounts when in root (/)
    # @override
    ls() {
        command ls "$@"  # Regular ls
        [[ "$PWD" == "/" ]] || return
    
        # List NFS/remote mounts (Linux-style)
        awk '$1 ~ /:\/.*$/ {print $2}' /proc/mounts | while read -r mnt; do
            command ls "$mnt" "$@" 2>/dev/null
        done
    
        # List Windows drives (e.g. /c /d /e...) in Git Bash
        for drive in /[a-z]; do
            [[ -d "$drive" ]] && command ls "$drive" "$@" 2>/dev/null
        done
    }
}

[ "${BASH_SOURCE[0]}" = "$0" ] && ls "$@"
