#!/usr/bin/env bash

declare -F requires &>/dev/null || {
    requires(){
        local cmd=("$@") err
        command -v "${cmd[0]}" > /dev/null 2>&1 || err="'${cmd[0]}' is not installed"
        if [ ! "$err" ] && [ "$2" ]; then
            [[ "$2" == *" "* ]] && cmd=("${@:2}")
            "${cmd[@]}" > /dev/null 2>&1 || err="'$1' is not running"
        fi
        [ "$err" ] && echo -e "\033[31;2m${err}\033[0m" >&2 && exit 2
    }
}

# Execute only if script is run directly (not sourced)
[[ "${BASH_SOURCE[0]}" == "$0" ]] && requires "$@"