#!/usr/bin/env bash

##
# ssl_expires function
# @version (2025-04-15)
# @checksum 4e5762946a86ef2fa5842a1448f78a256a06b01f75c53722bb3ab23788aec1c3
##
declare -F ssl_expires &>/dev/null || {
    ssl_expires() {
        local domain="$1"
        if [ -z "$domain" ]; then
            echo "Usage: ssl_expires <domain>"
            return 1
        fi
    
        echo | openssl s_client -servername "$domain" -connect "$domain:443" 2>/dev/null |
            openssl x509 -noout -dates
    }
}

[ "${BASH_SOURCE[0]}" = "$0" ] && ssl_expires "$@"
