#!/usr/bin/env bash

##
# sys_type function (7d1f5a0f534214bc07839dbf3e00382ea566f1498e73caf08edca71c3e9e7baa)
# @version (2025-04-08)
##
declare -F sys_type &>/dev/null || {
    sys_type(){
        [[ -z "${OSTYPE:-}" ]] && declare -gx OSTYPE="$(uname | tr '[:upper:]' '[:lower:]')"
        local os="${OSTYPE,,}"
        [ $# == 0 ] && echo "$os" && return
        local cond="${1:-}" && cond="${cond,,}"
        case "$cond" in
            mac|darwin|ios) [[ $os == darwin* ]] ;;
            linux|unix|gnu|solaris|android|sunos|bsd) [[ $os == *linux* || $os == *bsd* || $os == *solaris* || $os == *sunos* || $os == *android* || $os == *gnu* ]] ;;
            win) [[ $os == *cygwin* || $os == *mingw* || $os == *msys* || $os == *windows* || $os == win* ]] ;;
            *) [[ $os == "$cond"* ]] ;;
        esac
        return $?
    }
}

[ "${BASH_SOURCE[0]}" = "$0" ] && sys_type "$@"
