#!/usr/bin/env bash

##
# sys_type function (b503fa13ec146279419d8d457ce4c48be691935ee58b2f12844d92ff98263e9e)
# @version (2025-04-08)
##
declare -F sys_type &>/dev/null || {
    sys_type(){
        [[ -z "${OSTYPE:-}" ]] && declare -gx OSTYPE="$(uname | tr '[:upper:]' '[:lower:]')"
        local os="${OSTYPE,,}"
        [ $# == 0 ] && echo "$os" && return
        local cond="${1:-}" && cond="${cond,,}"
        case "$cond" in
            mac|darwin|ios) [[ $os == darwin* ]] ;;
            linux|unix) [[ $os == *linux* || $os == *bsd* || $os == *solaris* || $os == *android* || $os == *gnu* ]] ;;
            win) [[ $os == *cygwin* || $os == *mingw* ]] ;;
            *) [[ $os == "$cond"* ]] ;;
        esac
        return $?
    }
}

[ "${BASH_SOURCE[0]}" = "$0" ] && sys_type "$@"
