#!/usr/bin/env bash

declare -F user &>/dev/null || {
    user(){
        local result_var; [[ "$1" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] && local -r result_var="$1" && local -n result="$1" && shift
        [ "$result_var" ] || return 1
        local -r cmd="$1" && shift
        case "$cmd" in
            name) result="${SUDO_USER:-${USER:-$USERNAME}}";; # @see whoami, `id -u -n`
            is_root) [ "$UID" ] || declare -gx UID="$( id -u )"; [[ $UID -eq 0 ]] || return 1;; # @alias is_sudo
        esac
    }
}
