#!/usr/bin/env bash

declare -F usr_is_root >/dev/null 2>/dev/null || {
    # @alias is_sudo
    usr_is_root(){ [ "$UID" ] || declare -gx UID="$( id -u )"; [[ $UID -eq 0 ]] || return 1; }

    # @see whoami, `id -u -n`
    usr_name(){ echo "${SUDO_USER:-${USER:-$USERNAME}}"; }
}


